import os, json, time, pathlib, tempfile, shutil
from utils import rss, og_image, extract, summarize, tts, media, youtube, notebooklm

STATE_PATH = "state/last_item_id.json"

def load_state():
    if not os.path.exists(STATE_PATH):
        return {}
    with open(STATE_PATH, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return {}

def save_state(state):
    pathlib.Path("state").mkdir(parents=True, exist_ok=True)
    with open(STATE_PATH, "w") as f:
        json.dump(state, f, indent=2)

def ensure_notebooklm(post_url, post_title):
    # Optional step; safe to skip if not configured
    try:
        if not notebooklm.is_enabled():
            print("[NotebookLM] Skipped (not configured).")
            return
        nb_id = os.getenv("NOTEBOOK_ID")
        if not nb_id:
            nb_id = notebooklm.ensure_notebook()
            print(f"[NotebookLM] Using notebook id: {nb_id}")
        notebooklm.add_source(nb_id, post_url, post_title)
        notebooklm.create_audio_overview(nb_id, focus="Extended deep dive and key insights for a general audience", language_code="en")
        print("[NotebookLM] Audio Overview requested.")
    except Exception as e:
        print(f"[NotebookLM] Non-fatal error: {e}")

def maybe_generate_srt(text, mp3_duration_s):
    # Optional simplistic SRT (approximates timing by chunking text)
    upload_srt = str(os.getenv("UPLOAD_SRT", "false")).lower() == "true"
    if not upload_srt:
        return None
    from utils.subtitle import text_to_srt
    return text_to_srt(text, mp3_duration_s)

def run():
    feed_url = os.environ["SUBSTACK_FEED_URL"]
    latest = rss.fetch_latest_item(feed_url)
    if not latest:
        print("No items in feed.")
        return

    state = load_state()
    last_id = state.get("last_id")
    item_id = latest["guid"] or latest["link"]
    if last_id == item_id:
        print("No new posts.")
        return

    post_url = latest["link"]
    post_title = latest["title"]
    print(f"New post detected: {post_title} | {post_url}")

    # Optional: NotebookLM step
    ensure_notebooklm(post_url, post_title)

    # Extract article & produce long-form summary
    article_text = extract.get_article_text(post_url)
    if not article_text:
        article_text = latest.get("summary") or latest.get("title")
    long_summary = summarize.long_form_overview(article_text, post_title, latest.get("published"))

    # TTS to MP3
    mp3_path = "overview.mp3"
    tts.text_to_speech(long_summary, mp3_path)
    mp3_dur = media.get_audio_duration(mp3_path)

    # Fetch image
    image_path = og_image.get_image_for_url(post_url)

    # Build MP4
    out_mp4 = "out.mp4"
    media.image_and_audio_to_mp4(image_path, mp3_path, out_mp4)

    # Optional SRT
    srt_path = maybe_generate_srt(long_summary, mp3_dur)

    # Upload to YouTube
    yt_title = post_title
    yt_desc = f"Automated extended audio overview of: {post_url}\n\nThis video was generated by an automated pipeline."
    yt_tags = ["Substack", "Automation", "NotebookLM", "Audio Overview"]
    youtube.upload_video(out_mp4, yt_title, yt_desc, tags=yt_tags, srt_path=srt_path)

    # Save state
    state["last_id"] = item_id
    save_state(state)
    print("Done.")

if __name__ == "__main__":
    run()
